version: '3.8'

services:
  app:
    build:
      context: ./code
      dockerfile: Dockerfile
    container_name: student-api
    expose:
      - "8000"
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    restart: always



